"""Add bookmark table

Revision ID: f803220e00ad
Revises: e2f4a4dc69b9
Create Date: 2025-08-01 17:14:19.855232

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f803220e00ad'
down_revision: Union[str, None] = 'e2f4a4dc69b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
